# Generated by Django 3.0.8 on 2020-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cetegory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='Shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cetegory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
