# Generated by Django 3.0.8 on 2020-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200819_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
